microsoft/checkedc

- WishList.md
Create a list of projects that people could work on now or soon (in the next few months).
>  Add a wish list of projects.

- tests/bounds_declaration_parsing.c
This change adds feature tests for parsing bounds expressions in function parameter lists.  These tests are for the checkedc-clang pull request [Extend clang IR with bounds expressions and parse bounds expressions for parameters](https://github.com/Microsoft/checkedc-clang/pull/8).
> Add feature tests for parsing bounds expressions in function parameter lists

- tests/bounds_declaration_parsing.c
Bounds expressions for parameters can use parameters variables declared
at any point in the parameter list.  This means that bounds expressions must
be checked in a scope that contains all the parameters for the
parameter list.
- This change adds tests for that, by having bounds expressions for parameters
use parameters declared later in the parameter list.
- It also adds tests that subexpressions of bounds expressions can be
parenthesized expressions.
- Finally, this change adds tests that have misspelled contextual keywords
in bounds expressions.  These expressions should be rejected by a compiler.
These tests can be used also to test error messages and error recovery in
compilers for that situation.
> Test parsing bounds expressions in parameter list scopes. 

- tests/parsing/return_bounds.c
This change adds tests for parsing return bounds expressions in function
declarators and function types.
- The tests for function declarators that return array_ptr types are
straightforward.  array_ptr types avoid the problems of the
infix C type declarator syntax, at least for pointer types.
- There are additional tests for parsing return bounds expressions for
more complicated types, such as pointers to function types, function
types that return pointers to function types, and function declarations
that return  pointers to function types.
- There are variants of these additional tests for unchecked pointer types 
with bounds declared for them.  The interoperation support in Checked C
may lead to these types of bounds declarations.  The tests cover return 
bounds expressions  for …
> Add feature tests for parsing return bounds expressions.

- tests/parsing/member_bounds.c
This change adds feature tests for parsing member bounds.   This accompanies the pull request 23 for the checked-clang repo.
> Feature tests for parsing member bounds.

- spec/bounds_safety/core-extensions.tex
This finishes up addressing issue #11.  When we switched to the terminology of
checked and unchecked pointers, there was feedback that we should be very
clear about what is being checked.  Specifically, checked pointers check
bounds, but do not check memory lifetime.  This adds a paragraph to the
description of checked pointers making to clear that memory lifetime is
not checked.
> Update description of checked pointers.

- spec/bounds_safety/interoperation.tex
This addresses issue #20 by expanding the implicit conversions for pointers to arrays.  We now allow conversions from pointers to unchecked arrays to pointers to checked arrays.   This is needed to support passing unchecked multi-dimensional arrays to functions that have checked array parameters.
This change adds a notion of assignment compatibility.  Compatibility of types in C is similar to equality and is not directional.   We need a directional conversion, where source and destination matter.  Informally, we allow a type A to be converted to another type B if A and B are the same except that B has more checking.  
I considered defining a recursive notion of assignment compatibility for referent types that are pointers, but decided not to do that now.    It requires other changes to …
> expand implicit conversions for pointers to arrays

- spec/bounds_safety/core-extensions.tex
This addresses issue #22 by clarifying the rules for checked properties of multi-dimensional arrays constructed using typedefs.   If an array type has an element type that is an array type, the array type and element type must both either be checked or unchecked.   This is true even if the element type is a typedef'ed name.
- Clarify that the checked property of an array declarator is only propagated to nested array declarators.  It is not propagated to typedef bodies.
- It is an error if there is a mismatch in checked properties between an array type and an element type that is an array type.
- Improve the organization and wording of the text for checked multi-dimensional arrays.
> Typedefs and checked multi-dimensional arrays.

- spec/bounds_safety/checking-variable-bounds.tex
- spec/bounds_safety/design-alternatives.tex
This change adds a description of alternative bounds choices for &*e.  This finishes the remaining work for  issue #18.
> Alternative designs for bounds of address-of a pointer dereference.

- tests/parsing/checked_array_types.c
- tests/typechecking/checked_arrays.c
This change adds feature tests that the dimensions of a multi-dimensional array are either all checked or unchecked.   The Checked C spec requires this for multi-dimensional arrays.     It removes feature tests where individual dimensions could be declared as unchecked using the `unchecked` keyword.   These feature tests were for an experimental feature in the clang implementation of Checked C.  We have decided to stick with the existing wording in the spec.
This change also adds tests for parenthesized array declarators.   The checked property is supposed to propagate from the outer dimension of a multi-dimensional array to the inner dimension: `int a checked[10][10]` declares a checked array of checked arrays  This propagation wasn't happening when the declarator for the outer dimension …
> Test checked properties of dimensions of multi-dimensional arrays

- spec/bounds_safety/variable-bounds.tex
- tests/parsing/declaration_bounds.c
- tests/parsing/parameter_bounds.c
- tests/parsing/return_bounds.c
- tests/typechecking/bounds.c
There is a pull request for the checked-clang repo (https://github.com/Microsoft/checkedc-clang/pull/42) that adds checking of type requirements for bounds declarations to clang.  See the pull request for details. 
This commit adds the matching tests.   It includes both positive tests (that are supposed to work) and negative tests that should fail with an error message.    We have added the expected error message from the clang implementation for the negative tests, so that the tests can be used in the clang test infrastructure.  This commit also fixes issues in existing tests that the checking uncovered.
> Tests for checking type requirements for bounds declarations.

- tests/typechecking/bounds.c
This change adds tests for type checking bounds expression of the form bounds(e1, e2).  It tests both positive cases (that should type check) and negative cases (that should fail to type check).    This change matches a corresponding change in the checkedc-clang repo.  It addresses checkedc-clang repo issue 14.
.
> Test type checking of bounds range expressions

- include/stdchecked.h
- tests/parsing/checked_array_types.c
- tests/parsing/declaration_bounds.c
- tests/parsing/member_bounds.c
- tests/parsing/parameter_bounds.c
- tests/parsing/pointer_types.c
- tests/parsing/return_bounds.c
- tests/typechecking/bounds.c
- tests/typechecking/checked_arrays.c
- tests/typechecking/pointer_types.c
We're updating the clang implementation so that Checked C keywords start with an underscore and a capital letter. This avoids conflicts with existing C identifiers.
The keyword change follows the rules in the C Standard: all identifiers beginning with an underscore followed by a capital letter or underscore are reserved for implementation use.  This allows them to be used for language extensions without conflicting with existing identifiers. Of course, some programs do not follow the standard and use these identifiers.
This change adds a header file stdchecked.h that has macros that maps the existing non-prefix, lower case keywords to the new keywords.  It updates the tests to include that header file.
Testing:
- Updated version of clang passes these new tests.
> Change Checked C keywords to avoid conflicts with existing identifiers.

- tests/typechecking/bounds.c
- tests/typechecking/checked_arrays.c
- tests/typechecking/pointer_types.c
I updated some clang error messages to use the new type names `_Ptr` and `_Array_ptr` during the code review yesterday.   This caused some of the tests to break.  Update the tests..
> Fix test breaks due to type rename.

- tests/parsing/interop_types.c
This change adds tests for parsing of bounds-safe interface type annotations.   It matches a corresponding change for the checked-clang repo. 
The type annotations are a generalization of the `int * x : ptr` annotation described in the specification. That annotation does not provide a way to represent information for pointers with multiple levels of indirection (`int **x` for example). Instead of just using `ptr`, we now allow a type annotation to be specified.  The annotation has the form `type` `(` _type name_ `)`.   For example, a variable declaration `int **x` could be annotated as `int ** x : type(_Ptr<_Ptr<int>>)`.  This richer form allows us to represent bounds-safe interfaces where pointers are passed by reference, for example.
Bounds-safe interfaces are allowed for parameters, …
> Add tests of parsing interop type annotations.

- tests/parsing/interop_types.c
- tests/typechecking/interop.c
This change adds feature tests for implicit type conversions at bounds-safe interfaces.   It includes three sets of tests, corresponding to each language construct that can have a bounds-safe interface: a set for parameters with bounds-safe interfaces, a set for non-locally scoped variables with bounds-safe interfaces, and a set for members with bounds-safe interfaces.  These tests match corresponding compiler changes for Checked C clang repo issue 31.
For each set of tests, there are
- tests for assigning (or passing) checked pointers to unchecked pointers with bounds-safe interfaces (where the referent types match)
- tests for assigning or passing checked pointers to void * pointers with bounds-safe interfaces
- tests for passing checked void pointers to non void * pointers with …
> Feature tests for bounds-safe interface implicit type conversions.

- tests/parsing/interop_types.c
- tests/parsing/return_bounds.c
- tests/typechecking/interop.c
Add tests of misplaced return bounds expressions in complex declarators.
The tests also check the resulting error messages from the clang Checked C
implementation.  These tests are for Checked C clang repo issue 66.
This also fixes some cases where const type qualifiers were omitted in a
bound-safe interface t ype annotations.
> Test misplacement of return bounds expressions.

- tests/parsing/interop_types.c
- tests/typechecking/bounds.c
Return bounds declarations are only allowed for functions with return types that are integer or pointer types.   The clang error messages for this situation suggested an array type as a possibility.   Functions cannot return arrays, so we've update the clang error message.  Update the corresponding Checked C tests too.
> Improve error messages for return bounds declarations for incorrect types.

- tests/parsing/interop_types.c
- tests/parsing/return_bounds.c
- tests/typechecking/interop_type_annotations.c
This change adds feature tests for type checking of bounds-safe interface type annotations.  It matches Checked C pull request [https://github.com/Microsoft/checkedc-clang/pull/74](https://github.com/Microsoft/checkedc-clang/pull/74).
The are 4 groups of tests: tests for parameter types, tests for global variable types, tests for function returns, and tests for structure members.  For each group of tests, there are tests for types that can't appear as bounds-safe interface types, types that can't have bounds-safe interface type annotation, tests of valid annotations, tests of annotations where the interface type and the declared type are mismatched (not compatible types when the checked property on pointer and array types is disregarded), and tests of annotations where the interface type …
> Feature tests for checking bounds-safe interface annotations.

- tests/parsing/checked_array_types.c
- tests/parsing/declaration_bounds.c
- tests/parsing/interop_types.c
- tests/parsing/member_bounds.c
- tests/parsing/parameter_bounds.c
- tests/parsing/pointer_types.c
- tests/parsing/return_bounds.c
- tests/typechecking/bounds.c
- tests/typechecking/checked_arrays.c
- tests/typechecking/interop.c
- tests/typechecking/interop_type_annotations.c
- tests/typechecking/no_prototype_functions.c
- tests/typechecking/pointer_types.c
Calls to no-prototype functions are not type checked according to the C Specification (Section 6.5.2.2 of the C11 specification).  Because of this, the Checked C extension does not allow no-prototype functions to be redeclared to take or return checked types.   The lack of type checking at calls enables checking of bounds to be bypassed. Section 5.5 of the Checked C extension specification describes the restrictions.  In the terminology of the C Specification, no-prototype function types are incompatible with function types that take arguments or return values that have checked types, contain values with checked types embedded within them, or are recursively pointers to function types that take or return checked types or checked values.
This change adds feature tests that check that …
> Test redeclarations of no-prototype functions with checked types.

- spec/bounds_safety/core-extensions.tex
- spec/bounds_safety/variable-bounds.tex
This change addresses issue #53.  To avoid backward-compatiblity problems when using the
Checked C extension with existing C programs, we are changing the keywords for the
extension to start with an underscore followed by a capital letter.  
The updated keywords are:
``
_Array_ptr  _Checked  _Dynamic_check  _Ptr  _Span  _Where  _Unchecked 
``
This change adds a description of these keywords to the specification.  We use a header file 
that provides all-lowercase versions of the keywords.  The text and examples in the
specification continue to use the all-lowercase versions because that is the way extension is
intended to be used.
This change also clarifies that the syntax for bounds expressions uses specific identifiers,
not keywords.   This cuts down on the number of new keywords that …
> Change specification to describe updated Checked C keywords.

- spec/bounds_safety/variable-bounds.tex
Rearrange the order in which material is presented in Chapter 3 (bounds for variables) to flow more logically.
- Present the important concepts that programmers will need to know in earlier
sections.
- Move the more advanced technical material to later sections.  This includes
additional requirements on bounds declarations that programmers may need
to rarely consult.  It also includes support for non-relatively
aligned pointers and detailed technical descriptions of concepts such
as flow-sensitive bounds declarations.
- Update the description of bundled blocks to be more succinct and
direct.  Discuss the somewhat esoteric differences between e1, e2 and
e1; e2 in Checked C at the end of the section.
> Improve the ordering of material in Chapter 3.

- spec/bounds_safety/checking-variable-bounds.tex
- spec/bounds_safety/variable-bounds.tex
Update the title of Chapter 4 to be clearer.  The terminology
"check bounds" is ambiguous and could be misconstrued to be about
runtime bounds checks.  The chapter is really about checking bounds
declarations.
Update the title of "Extent of dataflow-sensitive bounds declarations"
to be "Extent of bounds declared at statements".  The terminology "dataflow"
is specific to compilers, so avoid it.
> Rename some sections.

- spec/bounds_safety/design-alternatives.tex
- spec/bounds_safety/interoperation.tex
- spec/bounds_safety/variable-bounds.tex
This changes updates the Checked C specification to describe how function types are extended with bounds information.  This addresses issue #69.
-  It adds a section to Chapter 3 (bounds for variables) that describes how function types and function pointer types include bounds information.   The section includes a description of how type compatibility changes for function types.
- It updates the rules for casts in Chapter 5 (interoperation)  to include function pointers.
- It adds a section to bound-safe interfaces in Chapter 5 that describes how function types with bounds-safe interfaces are compatible with function types without bounds information.   This is crucial for allowing redeclarations of existing library functions with bounds information.
For now, we have simple rules for …
> Extend function types with bounds information

- spec/bounds_safety/interoperation.tex
Wonsub Kim found some typos in the examples and non-examples for implicit casts.  This change incorporates his fixes for the typos.
> Fixes for typos in implicit casting examples.

- spec/bounds_safety/interoperation.tex
This change reworks the bounds-safe interface section.  It adds a description of bounds-safe interface types and brings the section up-to-date with the clang implementation.  This addresses issue #60.
The text for the section needed to be revised substantially so that it accurately describes that programmers can use bounds declarations or bounds-safe interface types, depending on what needs to be described.  While I was doing that, I improved the writing and organization of the section.   I shortened up some descriptions.  I moved sections on type checking and checking of bounds declarations that are primarily for language designers and compiler writers to the end of the section.  I also added a description of the organization of the section.
> Add description of bounds-safe interface types.

- tests/parsing/return_bounds.c
- tests/typechecking/bounds.c
- tests/typechecking/interop_type_annotations.c
This change corresponds to an update to the Checked C clang implementation to do better checking of bounds declarations and bounds-safe inferface type annotations for function pointer types.
This change fixes errors in existing tests found by the improved checking:
- Fix an error in parsing\return_bounds.c where there is a count bounds expression used with a function return type of `int`.
- Fix errors  in typechecking\interop_type_annotations.c where lack of parentheses led interface types being declared for the wrong return types.
For example, the annotation type declared here:
```
int (*g80)(int *, int *) : itype(ptr<int(int *, int *)>)`
```
is the interface type for the return value of `g80`, which has type `int',  not the interface type for g80 as intended.  Add parentheses to fix …
> Test checking of bounds declarations for function pointer types.

- include/fenv_checked.h
- include/inttypes_checked.h
- include/math_checked.h
- include/signal_checked.h
- include/stdio_checked.h
- include/stdlib_checked.h
- include/string_checked.h
- include/threads_checked.h
- include/time_checked.h
- spec/bounds_safety/interoperation.tex
- tests/typechecking/bounds.c
- tests/typechecking/no_prototype_functions.c
- tests/typechecking/redeclarations.c
- tests/typechecking/redeclare_libraries.c
This change adds tests of redeclarations of functions with bounds declarations.  This  matches a corresponding change for the Checked C clang implementation.  The tests check that functions can be redeclared with identical bounds declarations on parameters and returns.  They also check that error messages are produced when the bounds declarations are not identical. This change also checks redeclarations of functions with bounds-safe interfaces. For now, the bounds declaration must be syntactically identical modulo parameter names.  Later this will be changed to require that the bounds declaration be provably semantically identical.
To further test redeclarations of functions, this change also adds header files that redeclare functions in the C standard library with bounds-safe interfaces, …
> Test redeclarations of functions with bounds declarations.

- tests/parsing/declaration_bounds.c
- tests/typechecking/redeclarations.c
This adds tests for:
- variables with unchecked pointer type or unchecked array type and bounds-safe interfaces.
- variables with checked pointer type or checked array and bounds declarations.
- locally-scoped variables that hide global variables.
- locally-scoped extern variable declaration.
For now, we require that bounds expressions be identically syntactically when they need to match.  This will be generalized later.
> Add tests for redeclarations of variables with bounds.

- spec/bounds_safety/checking-variable-bounds.tex
This updates the checking of bounds declaration to handle lexically-hidden variables.  This address issues GitHub issue #75.  Block-scoped variables that hide other variables need to be renamed before checking.   This change also fixes a few typos in that section.
> Update checking of bounds declarations to handle lexically-hidden variables.

- spec/bounds_safety/structure-bounds.tex
- Add a definition of structure type compatibility across compilation units.  This addresses Github issue #74.  This is mostly of theoretical interest because C compilers do not typically check compatibility of  structure types across C compilation units.
- Update the text to match changes made to variable bounds declaration for typing rules and bounds-safe interface types.
- Be more precise with terminology, differentiating between member bounds and member bounds declarations.
> Improve section on bounds for structure types.

- spec/bounds_safety/interoperation.tex
- spec/bounds_safety/variable-bounds.tex
Add a paragraph describing bounds declarations for integer-typed variables.   These are needed when a pointer is cast to an integer that is then assigned to a variable.  This brings the specification into agreement with the clang Checked C implementation, which already allows this.    This address issue #79.
Also fix some typos in the interoperation section and clarify some wording.
Adjust the tag in the example to only be one-bit wide.   There are some additional complications with handling multi-bit tags.   See GitHub issue #89 for details.  To avoid these complications, we just change the example to use a 1-bit tag.
> Allow bounds declarations for integer-typed variables.

- include/inttypes_checked.h
This addresses issue #93.   In the tests of bounds-safe interfaces for `wcstoimax` and `wcstoumax`, we are only including `<inttypes.h>`. We are not including `<stddef.h>`. This results in a test failure on a Linux x64 Ubuntu box because `wchar_t` is missing.  The fix is to add the missing include.
Testing:
- Test now passes on Linux Ubuntu x64.
- Test continues to pass on Windows x86.
> Fixing missing header file include for test.

- tests/typechecking/bounds.c
- tests/typechecking/no_prototype_functions.c
- tests/typechecking/pointer-sized-long-long/lit.local.cfg
- tests/typechecking/pointer-sized-long-long/pointer_casts.c
- tests/typechecking/pointer-sized-long/lit.local.cfg
- tests/typechecking/pointer-sized-long/pointer_casts.c
The C Standard is purposefully vague on the subject of the size of pointers, and their comparison to the size of various integral types.
Here, we split the tests that contain integer <-> pointer casts into two groups. In the first group (the vast majority of platforms), `void*` is the same size as `long`, so we do all our casts to `long`s. In the second group (notably including Win64), `void*` is not the same size as `long`, but it is the same size as `long long`, so we do all our casts to that.
The only place this approach doesn't work is with Enums, which have an implementation-defined size (according to my reading of the spec), so I've commented out the pointer->enum casts. 
Fixes #92
> Fixes non-portable casts in tests

- tests/parsing/declaration_bounds.c
- tests/parsing/member_bounds.c
- tests/static_checking/initializers.c
- tests/typechecking/bounds.c
- tests/typechecking/redeclarations.c
This change matches a corresponding change in the Checked C clang repo (https://github.com/Microsoft/checkedc-clang/pull/110). The compiler will be checking that automatic variables with _Ptr types or bounds declarations are always initialized using an initializer.
This adds missing initializers to existing tests.  It also adds tests that the compiler produces errors for uninitialized automatic variables.
Note that static variables are always initialized to 0, if they do not have an initializer.  This means that we do not have to check that they are initialized.  0 is valid for any bounds declaration, so it works well as
a default initialization value.
> Update tests to ensure automatic variables are initialized.

- tests/dynamic_checking/failing-arith-dynamic_check.c
- tests/dynamic_checking/failing-simple-dynamic_check.c
- tests/dynamic_checking/passing-arith-dynamic_check.c
- tests/dynamic_checking/passing-simple-dynamic_check.c
This updates some of the tests for Microsoft/checkedc-clang#128 to make sure we get some warnings on super-simple dynamic checks that will fail. 
We probably want to be careful to only use the `-verify` flag in a few tests, so the tests are not too coupled to clang's constant folder/default optimization level/the accuracy of our implemented static analysis. I think it's fine in these tests, but probably no others.
> Adds Verification of Explicit Dynamic Check Warnings

- include/stdlib_checked.h
- tests/static_checking/nme_bounds.c
These are the tests to go along with Microsoft/checkedc-clang#129
I've had to comment out the checked version of `wctomb` because the bounds use a macro that expand into a call.
> Adds non-modifying expressions check for bounds annotations

- spec/bounds_safety/variable-bounds.tex
As discussed in person, and in #101.
There's no explicit formal grammar for non-modifying expressions, should there be?
> Disallow commas at the top-level of non-modifying expressions.

- tests/static_checking/nme_bounds.c
- tests/typechecking/function_casts.c
- tests/typechecking/pointer-sized-long-long/function_casts.c
- tests/typechecking/pointer-sized-long/function_casts.c
These tests all fail on x86_64.
I think I'm happy enough with coverage that we can get rid of them, but I'll defer to david.
> Fixes Tests that rely on int->ptr conversions

- spec/bounds_safety/interoperation.tex
This brings the specification closer to our compiler's rules for function pointer casts. 
This one will probably need work, specifically around "change the value of" in the language I have added.
> Clarifies Function Pointer Casts

- tests/parsing/pointer_types.c
- tests/typechecking/checked_arrays.c
- tests/typechecking/pointer_types.c
The compiler now checks that assignments through array_ptrs and reads through array_ptrs use array_ptrs that have bounds.   These checks found some tests where bounds declarations are missing for array_ptr variables.  Add the missing bounds declarations.   
The compiler also found tests where an unchecked pointer with unknown bounds is incorrectly cast to a checked pointer Remove those tests.
> Add missing bounds declarations.

- tests/typechecking/pointer-sized-long-long/function_casts.c
- tests/typechecking/pointer-sized-long/function_casts.c
- tests/typechecking/pointer-sized-long/pointer_casts.c
These were fixes that I should have caught earlier. My fault entirely. 
This is to do with the fact that the "!" operator always returns an int, but on most platforms you can't just cast that directly to a pointer, so we cast it to the correct number size then cast it to a pointer.
> Fixes to function casts on 64-bit

- tests/typechecking/checked_arrays.c
- tests/typechecking/pointer_types.c
We are adding a check to the compiler that the source expressions of casts
to ptr types have bounds.  This uncovered a number of tests where the
source expressions do not have bounds.  Usually, the problem was a cast
from a variable with unchecked pointer type to T to ptr<T>.  The fix is to
use an expression that has known bounds instead, such as an expression
that takes the address of a variable with type T.
> Fix casts of sources with unknown bounds to ptr types.

- include/_builtin_stdio_checked.h
- include/_builtin_string_checked.h
- include/stdio_checked.h
- include/string_checked.h
This is a first pass at making the build pass on mac.
Apple defines the `__APPLE__` constant, which we can use to find out if we're on mac. For the moment I'm just not defining our checked versions of these stdlib functions if we're on a mac, I want to circle back around to getting the definitions correct, but this may take some time because of how Apple have structured their C system headers. 
Expect another commit which provides alternative definitions which we can actually use on Macs.
> Fixes issues with checked system headers on Mac with ifdefs

- tests/dynamic_checking/deref-arith-check-opt.c
- tests/dynamic_checking/deref-arith-check.c
- tests/dynamic_checking/deref-check-opt.c
- tests/dynamic_checking/deref-check.c
- tests/dynamic_checking/failing-arith-dynamic_check.c
- tests/dynamic_checking/failing-simple-dynamic_check.c
- tests/dynamic_checking/subscript-check-opt.c
- tests/dynamic_checking/subscript-check.c
This way processes exit gracefully, instead of relying on the OS to handle
a crash.  On Windows, crashes cause Windows Error Reporting (WER) to fire up,
invoking system logging.
We have been using the not program from the LLVM test harness with the --crash
option to determine when processes have exited with a crash.  We have found
that this approach is not working reliably on Windows.  The not program spawns
a child process and looks at the process exit code, looking for negative exit
codes to indicate a crash. When running automated testing under Visual Studio
Team Services, sometimes the exit code is a positive number.
Testing:
- Tested this change on Windows and Linux and all the Checked C tests passed as expected.
> Use signals for out-of-bound memory access tests.

- samples/2_8_append.c
This sample uses `size_t`, which is in `stddef.h`. I forgot that header when originally writing this sample, this fixes it and allows the sample to compile.
> Adds Missing Header to Sample 2.8

- tests/dynamic_checking/README.md
- tests/dynamic_checking/increment-deref-arith-check-opt.c
- tests/dynamic_checking/increment-deref-arith-check.c
- tests/dynamic_checking/increment-deref-check-opt.c
- tests/dynamic_checking/increment-deref-check.c
- tests/dynamic_checking/increment-subscript-check-opt.c
- tests/dynamic_checking/increment-subscript-check.c
- tests/dynamic_checking/read-deref-check.c
- tests/dynamic_checking/update-deref-arith-check-opt.c
- tests/dynamic_checking/update-deref-arith-check.c
- tests/dynamic_checking/update-deref-check-opt.c
- tests/dynamic_checking/update-deref-check.c
- tests/dynamic_checking/update-subscript-check-opt.c
- tests/dynamic_checking/update-subscript-check.c
- tests/dynamic_checking/write-deref-check.c
This adds high-level tests of compound assignment and increment operators to our codebase.
Given these tests are all very similar, we saw fit to document the structure of the tests in this directory for future maintainers/testers.
> Dynamic bounds check array update

- tests/typechecking/checked_scope.c
- simple version of checked scope parsing & type checking
- checked function
- checked keyword is before function definition and it is used as function specifier
- in checked function, it checks if function declaration(return & parameter) is checked scope
- in checked function, it checks if function definition(function statement boyd) is checked scope
- in checked function, function with no prototype is not allowed
- checked scope
- checked keyword is before l_brace and corresponding compound statments are affected by checked scope
- in checked scope, checked pointer or unchecked pointer with bounds-safe interface is only allowed
- in checked scope, child scope inherits parent checked property
> + Add test code for checked scope implementation (#189)

- include/stdio_checked.h
- include/stdlib_checked.h
Before this change, it was required that programmers were careful with the order in which they included headers - in particular, the inclusion of `<stdchecked.h>` must come after the final inclusion of `<stdlib_checked.h>` or the final inclusion of `<stdio_checked.h>`, whichever came later.
This is a problem if you want to be able to use the `ptr<T>` in a header file rather than `_Ptr<T>`, especially as this almost definitely brings the include of `<stdchecked.h>` earlier.
The solution is to rename these parameters. As these are declarations, all that matters is the types are compatible, the names are effectively erased (even if we use them in a `count(e)` or `bounds(e1, e2)` expression, these are canonicalised to argument position rather than name.
> Renames parameters called 'ptr' in checked headers

- tests/typechecking/checked_arrays.c
- tests/typechecking/checked_scope.c
- tests/typechecking/pointer_types.c
Test code is modified to apply checkedc-clang modification for checked block implementation
1. implicit cast rule has changed to allow implicit cast between checked pointer types
Therefore, previous expected-error is changed to expected-correct
pointer_types.c & checked_arrays.c is modified file in checkedc test program
2. related checked_scope test code is extended
- check if No-use of unchecked pointer/array type in checked block
- check if No-use of unchecked pointer type casting in checked block
- changed semantic of address-of operator in checked block
> Add & modify test code for checked scope feature (#189) and related work-item(#201, #202)

- spec/bounds_safety/core-extensions.tex
- tests/typechecking/checked_scope_pragma.c
+ it works well with corresponding latest checkedc-clang implementation
+ simplify test code for BOUNDS_CHECKED pragma
+ #pragma BOUNDS_CHECKED on
+ In checked scope of compilation unit
Test unchecked function specifier
By default, all functions are checked function
By default, all global variables are checked type
By default, all structures are checked type
Function parameter & return values SHOULD be checked type in checked scope of compilation unit
Also, local variables, global variables, structure members SHOULD be checked type
+ modify specification related to BOUNDS_CHECKED pragma value
+ BOUNDS_CHECKED on-off-switch value can be [on|off]
+ default value is off
> simplify and extend test code in checked_scope_pragma.c (#135)

- spec/bounds_safety/core-extensions.tex
- tests/typechecking/checked_scope.c
- tests/typechecking/checked_scope_pragma.c
+  Add test code for variable argument function call in checked block (#251)
+ Variable argument function call is not allowed in checked blocks
+ variadic function call & printf function call is checked
+ Add test code for BOUNDS_CHECKED pragma (#247)
+ For elaborate test BOUNDS_CHECKED pragma with a scope, add test cases
+ For elaborate scope handling, implementation is changed to use annotation token
By using annotation token, it can recognize scope corresponding to annotation token
+ Restore on-off-switch syntax in pragma BOUNDS_CHECKED
+ #pragma BOUNDS_CHECKED [on-off-switch]
+ on-off-switch = ON/OFF/DEFAULT
>  Add test code for variable argument function call issue in checked block (#251) & BOUNDS_CHECKED pragma (#247)

- tests/parsing/pointer_bounds_cast.c
This is the test code for the pointer bounds casting. (#204)
- It will be added more test cases.
> Add test code for dynamic and assume bounds cast (#204)

- spec/bounds_safety/checkedc.tex
- spec/bounds_safety/checking-variable-bounds.tex
- spec/bounds_safety/core-extensions.tex
- spec/bounds_safety/design-alternatives.tex
- spec/bounds_safety/interoperation.tex
- spec/bounds_safety/introduction.tex
- spec/bounds_safety/open-issues.tex
- spec/bounds_safety/related-work.tex
- spec/bounds_safety/simple-invariants.tex
- spec/bounds_safety/variable-bounds.tex
The span type seems like a type that is better suited for a library than a core
language extension. In C++, which has templates, there is already a proposal
for adding a span-like type to the C++ Standard Library.  Remove the span
type for the language extension design and move it to the design alternatives
section.
To be clear, we are postponing adding the span type to the language extension
design (and the clang implementation as well).   We may decide to add it in
the future, especially because implicit conversions involving library types
and pointers can be messy.  However, for now,  it can wait until the need
becomes clearer.
This commit also changes the version description to "Version 0.7 - Draft" and
changes the returned by the address-of operator in checked block from ptr
to …
> Remove span type from the language extension design.

- tests/dynamic_checking/read-member-arrow-pointer-check.c
This matches a corresponding compiler change to fix issue 280 in the checkedc-clang repo.
> Test reads of members with bounds using the arrow operator.

- tests/typechecking/checked_scope.c
+ Add test code for function pointers in checked block(checkedc-clang/#272)
+ address-of (&) operator produces checked ptr<T> type
However, array_ptr<FunctionType> is not proper if address-of operator is applied to function type
For checked function pointer, it produces ptr type not array_ptr
+ checked -ast-dump output. AST dump output is also added
> + Add test code for function pointers in checked block(checkedc-clang/#272)

- tests/typechecking/checked_scope.c
+ Add test code for (checkedc-clang/#277) issue
+ prevents bounds cast operation to unchecked type in a checked scope
+ prevents _Assume_bounds_cast operation in a checked scope
> Add test code for (checkedc-clang/#277) issue

- tests/parsing/pointer_bounds_cast.c
- tests/static_checking/static_check_bounds_cast.c
. Add syntax check for *_bounds cast expression with bounds expressions.
ex)
array_ptr<int> x : count(10)
= _Dynamic_bounds_cast<array_ptr<int>>(x, count(10));
array_ptr<int> x : count(10)
= _Dynamic_bounds_cast<array_ptr<int>>(x, bounds(a, b));
. Add test code to check whether E1 is pointer type or integral type.
> Add test code for bounds cast expression (#286)

- tests/static_checking/static_check_bounds_cast.c
The type checking of bounds_cast expressions was improved, so an error message needs to be updated.
> Update error message for bound_cast test.

- tests/dynamic_checking/bounds/deref_opt.c
The prior commit failed automated testing on Linux because there were backward slashes in clang test automation commands that needed to be forward slashes, causing files to not be found.  This commit fixes that.
Testing:
- Passed automation testing on Linux.
> Fix backward slashes in clang test automation commands.

- tests/typechecking/checked_scope.c
+ Add test code for bounds-safe interface of function return type (checkedc-clang/#302)
> Add test code for bounds-safe interface of function return type (checkedc-clang/#302)

- tests/typechecking/checked_scope.c
+ Add test code for KNR parameter function call in checked scope (checkedc-clang/#304)
+ KNR parameter function call is prevented in checked scope
since its function call has no-prototype function prototype
> Add test code for KNR parameter function call in checked scope (checkedc-clang/#304)

- include/_builtin_common.h
- include/_builtin_stdio_checked.h
- include/_builtin_string_checked.h
- include/fenv_checked.h
- include/inttypes_checked.h
- include/math_checked.h
- include/signal_checked.h
- include/stdio_checked.h
- include/stdlib_checked.h
- include/string_checked.h
- include/threads_checked.h
- include/time_checked.h
This is the follow-on to Microsoft/checkedc-clang#311
This should solve any problems relating to casts to unchecked pointers in checked scopes.
I'll do a second PR where I port this change to the test suite and see if we can remove some more unchecked lines/functions.
> Cast to checked array pointers in bounds declarations

- include/CMakeLists.txt
- include/_builtin_common.h
- include/_builtin_string_checked.h
- include/stdio_checked.h
A Variety of changes
- Removing some `_Unchecked` annotations
- Adding interop type to `__builtin_object_size`
- Adding interop types for `stdin` `stdout` and `stderr`
- Adding interop declaration for `fputc`
There will be more changes incoming, as I complete other benchmark conversions. This branch is what I'm using when testing my changes.
> Header Fixups from Benchmark Conversion

- include/stdio_checked.h
Stdio_checked.h is failing to compile on Windows (issue #169).  Bounds-safe
interfaces were added for stdin, stdout, and stderr.  These identifiers only
have to be expressions with type FILE *.  On Windows, they are function calls,
so we add a bounds-safe interface for the function being called.
> Fix stdio_checked.h for Windows.

- include/string_checked.h
I should not be trusted with De Morgan's Laws, turns out I'll break them.
`!a && b` is not equivalent to `!(a && b)`.
This should make anagram work on Linux again, I tested it on my WSL installation
> Correct Conditionals for apple system header support

- tests/parsing/typevariable/forany_parsing.c
- tests/parsing/typevariable/forany_parsing_error.c
For testing scope, it's incorporated in both forany_parsing.c and forany_parsing_error.c
forany_parsing.c : 
* It tests that you can create a variable of type T, if T is a type variable declared in _For_any. 
* It also tests that creating a new _For_any scope does not break function body scope. More specifically, it makes sure that all the parameters are usable in function body as well as new type variables.
* Also tests that function declaration is added to the right scope, by calling the function in a different function. If the function declaration is registered in _For_any scope, upon exiting function declaration, the function name will not be available.
forany_parsing_error.c:
* Tests to make sure that a type T, declared in _For_any specifier, cannot be used outside of function …
> Adding test files for _For_any specifier and type variable declarations.

- tests/parsing/typevariable/forany_parsing.c
- tests/parsing/typevariable/forany_parsing_error.c
For_any parsing is generating LLVM IR files as part of test runs.  This causes automation testing to fail because it creates the file in a source directory.   The next automation run fails because it finds a file with no RUN line in it in the test directory.  The fix is to not generate LLVM IR files.
> Stop generating LLVM IR as part of testing forany_parsing.

- tests/parsing/typevariable/forany_parsing.c
- tests/parsing/typevariable/forany_parsing_error.c
forany_parsing.c test did not pass, because it does not have <type, ...> in generic function call. This test case was written before implementing generic function call.
> Fix test error after generic func call

- tests/static_checking/bounds_expr_equality.c
This implements tests for https://github.com/Microsoft/checkedc-clang/issues/107
As part of statically checking bounds declarations, we need to check symbolic equality of expressions and to lexicographically order expressions (for sorting commutative operands).  This implements language-level tests of bounds declarations that indirectly cover lexical equality/inequality.
> Add tests for lexical equality of expressions.

- tests/typechecking/checked_scope.c
- tests/typechecking/pointer_types.c
These are the minimal changes to get the checkedc tests working against the improved bounds inference algorithm from Microsoft/checkedc-clang#336.
Later the improved inference will need many more tests.
> Updates Tests for Improved Bounds Inference

- tests/parsing/typevariable/forany_parsing.c
- tests/parsing/typevariable/forany_parsing_error.c
With the introduction of type variable types in clang, it is important to make sure that generic functions are a FunctionProtoType. We did not allow generic functions to be FunctionNoProtoType. In order for the tests to work correctly, I had to add "void" in () if there are no parameters.
> Change function declaration to be prototyped.

- tests/typechecking/checked_scope.c
Add test case for old-style K&R definitions that are preceded by prototypes in checked scopes.
> Add test case for K&R definition preceded by prototype.

- tests/static_checking/static_check_bounds_cast.c
- tests/typechecking/checked_scope.c
- tests/typechecking/checked_scope_pragma.c
- tests/typechecking/interop.c
Checked C clang pull request https://github.com/Microsoft/checkedc-clang/pull/363 addresses the problem that bounds-safe interfaces on function pointers were not being used during type checking.  It substantially revised the error messages for cases where the term "unchecked type" might be unclear to programmers (for example, a function or array type that uses an unchecked type). 
This updates the error messages in the existing Checked C tests.  It also adds tests of typecheckng function pointer types involving bounds-safe interfaces.
> Revamp error messages for uses of unchecked types in checked scopes.

- tests/typechecking/checked_arrays.c
- tests/typechecking/function_casts.c
- tests/typechecking/interop.c
- tests/typechecking/pointer_types.c
- Update tests to allow conversions from any kind of checked pointer to
any kind of checked void pointer (ptr<void> and array_ptr<void>).
- Test that implicit conversions between void pointers and checked function
pointers are not allowed.  This is a common C extension that should
not be allowed for checked function pointers.
> Update tests involving void pointers.

- include/stdlib_checked.h
- tests/typechecking/malloc_free.c
the `free` function is unique as it has to be polymorphic over all three pointer kinds, unchecked pointers, ptrs, and array_ptrs. 
There are several potential interface types for `free`. They are:
1. `void free(void* p);` No interface type. Doesn't work as no implicit casts between checked ptrs and unchecked ptrs)
1. `void free(void* p : itype(_Ptr<void>));` ptr interface type. Doesn't let you pass array_ptrs to `free`.
1. `void free(void* p : itype(_Array_ptr<void>));` array_ptr interface type. Doesn't let you pass ptrs to `free`, for complex (soon-to-be-relaxed) reasons involving banning casts involving checked pointers to void.
1. `void free(void* p : count(1))` relies on knowing the size of void which is potentially undefined (but 1 byte in clang).
1. `void free(void* p : …
> Correct Interface Type of free()

- tests/typechecking/checked_scope.c
- tests/typechecking/interop.c
Add tests for returning checked pointers from functions with bounds-safe interfaces for their return values.  Modify an existing test to allow this behavior.   
These tests are for the compiler change in https://github.com/Microsoft/checkedc-clang/pull/368.
> Test returning a checked pointer from a function with an interop type.

- spec/bounds_safety/checkedc.tex
- spec/bounds_safety/core-extensions.tex
- spec/bounds_safety/introduction.tex
- spec/bounds_safety/variable-bounds.tex
This change adds a new type `nt_array_ptr` that is a variant of `array_ptr` for pointers to null-terminated arrays.   The change:
- describes the new type in core-extensions.tex.   
- describes a new checked null-terminated array type go with `nt_array_ptr`
- describes the runtime bounds checking rules for nt_array_ptr.
Most of the rules later in the specification for `array_ptr` apply to `nt_array_ptr`.    I initially started down the route of updating all occurrences of `array_ptr` to say "or `nt_array_ptr`".   I decided that was resulting in lots of changes that didn't help understanding much and made the text longer.   There is a paragraph in the description of `nt_array_ptr` that says that the rules for `array_ptr` usually apply to `nt_array_ptr` and that we mention `nt_array_ptr` …
> Add variant of array_ptr for pointers to null-terminated arrays.

- tests/static_checking/bounds_decl_checking.c
- tests/typechecking/checked_arrays.c
When a function parameter has bounds, corresponding call arguments should have bounds.  This adds tests that check that.   This corresponds to the compiler changes for https://github.com/Microsoft/checkedc-clang/issues/373,
> Add tests that check that call arguments have bounds.

- tests/dynamic_checking/bounds/array-bounds-decls.c
Add tests of uses of variables and fields with array types where
bounds are also declared.  The declared bounds should override the bounds
based on the array type.  This matches a corresponding Checked C compiler change.
These tests check that bounds checking is being done against the declared bounds.
For arrays with known size, the declare bounds should be smaller than the bounds
based on the type.   Accessing an element above the declared bounds should fail.
Also test variable-length arrays at the ends of structs.  Without using the declared
bounds, they have unknown bounds and can't be accessed in checked code.
> Test uses of declared bounds for arrays if present.

- tests/dynamic_checking/bounds/bounds-safe-interfaces.c
Variables and members with unchecked types may have bounds-safe interfaces.
When they are used in checked scopes, they should be treated as though they
have checked types.  This means that accesses to memory using pointers
stored in those variables or member should be bounds checked.
The changes adds tests of bounds checking of global and local variables with
bounds-safe interfaces and struct members with bounds-safe interfaces.  This
completes the work for issue #339.
> Test bounds checking for variables with bounds-safe interfaces.

- tests/static_checking/static_check_bounds_cast.c
PR #155 was meant to address this, but it was never completed.   We should not have uses of uninitialized variables in static_check_bounds_cast.c because that is undefined behavior.
> Fix uninitialized variables in static_check_bounds_cast.c

- include/stdchecked.h
- tests/parsing/checked_array_types.c
- tests/parsing/pointer_types.c
- tests/typechecking/bounds.c
- tests/typechecking/checked_arrays.c
- tests/typechecking/pointer_types.c
This change adds tests for parsing and typechecking the new Checked C null-terminated array and pointer types.  This matches a corresponding Checked C clang compiler pull request (https://github.com/Microsoft/checkedc-clang/pull/394).  The changes are integrated into existing test cases for checked arrays and array_ptrs.  
The tests for parsing are straightforward.  The new keywords `nt_checked` and `nt_array_ptr` can be used in place of the `checked` and `array_ptr` keywords.  For type checking, we add tests for building the new types. We check that null-terminated arrays and pointers can only be built from integer or pointer types (the assumption is that 0 is the null-terminator value, so only types for which 0 is a valid value can be used).
We also add tests that cover implicit …
> Test parsing and type checking of null-terminated arrays and pointers.

- include/stdio_checked.h
- tests/dynamic_checking/bounds/array-bounds-decls.c
- tests/static_checking/initializers.c
- tests/typechecking/checked_scope_basic.c
This change corresponds to a matching compiler [change](https://github.com/Microsoft/checkedc-clang/pull/396) that adds support for string literals with checked types and completes support for initialized checked data.   The language rules for string and array literals are discussed in issue #207 (they haven't been added to the Checked C specification yet).
The compiler change also improves error messages for types that occur syntactically in expressions and are used in checked scopes.  Those types must be checked and everything they use must be checked too.   This change updates checked_scope_basic.c to use new error messages.
Testing:
- Passes automated testing with the updated compiler.
> Test strings with checked types and initialized checked data.

- spec/bounds_safety/core-extensions.tex
The Checked C specification proposed omitting the null terminator from the number of elements in a null-terminated array.   This would allow the count of elements to be identical for both the array and the bounds for an `nt_array_ptr`.  However, this is not how null-terminated string literals work in C.    String literals have an array type that includes the null terminator element in the size of the array.
To match existing C behavior, we now include the null terminator in the size of null-terminated checked arrays.  This updates the specification accordingly.
> Include null terminators in the number of elements for null-terminated arrays.

- spec/bounds_safety/checkedc.tex
- spec/bounds_safety/checking-variable-bounds.tex
- spec/bounds_safety/design-alternatives.tex
- spec/bounds_safety/interoperation.tex
- spec/bounds_safety/structure-bounds.tex
- spec/bounds_safety/variable-bounds.tex
The bounds expression bounds(none) has a potentially ambiguous English meaning.   The bounds could be unbounded or be unknown.  This replaces the bounds expression bounds(none) with bounds(unknown) in the specification.  This is mostly a search-and-replace of the boundsnone macro.  I also updated the text that defines the meaning of the bounds expression.
> Replace bounds(none) with bounds(unknown) in the specification.

- tests/dynamic_checking/bounds/nullterm_pointers.c
Checked C allows reads at exactly the upper bound for null-terminated pointers
so that the potential terminating value can be examined.
This change adds new dynamic tests that check  that the the memory location at
the upper bound is accessible for null-terminated array pointers, and not
accessible for non-null-terminated array pointers.
> Test bounds checking for null-terminated pointers.

- tests/static_checking/initializers.c
- tests/typechecking/checked_arrays.c
- tests/typechecking/interop_type_annotations.c
The compiler was using the keywords `checked` and `nt_checked` when it should have used the full names `_Checked` and `_Nt_checked`.
> Update error messages that include checked array type names.

- samples/string-helpers.c
Here are some examples of using null-terminated strings adapted from K&R.   The code illustrates some basic aspects of using strings, as well as the sometimes trickier aspects of writing to a string.
I plan to clean up the code once the compiler change for making count(0) be the default bounds for nt_array_ptr is complete.
> Add examples of using null-terminated strings.

- tests/static_checking/bounds_decl_checking.c
- tests/typechecking/checked_arrays.c
- tests/typechecking/pointer_types.c
- tests/typechecking/redeclarations.c
Null-terminated array pointers have a default bounds of count(0).   This adds tests of bounds checking and type checking for null-terminated array pointers with programmer-specified bounds and default bounds.   This change matches a corresponding clang compiler change (https://github.com/Microsoft/checkedc-clang/pull/406).
There need to be additional tests added of struct members with default bounds of count(0).   I'd like to commit the compiler change soon to unblock people, so I'm opening this PR now, even though further work is needed.
> Test default bounds for null-terminated array pointers

- include/stdio_checked.h
- samples/find-pattern.c
The example is adapted from a simple "pattern finding" program from "The C Programming Language, Second Edition", by Kernighan and Ritchie.  The example uses only checked code.    The example does output using fputs; I updated fputs and the rest of stdio_checked.h with annotations for strings.
This example requires the compiler changes in https://github.com/Microsoft/checkedc-clang/pull/406 to compile.  I had to fix two bugs, which I'll add to the compiler pull request soon.
> Add another example of using strings and add string support to stdio_checked.h

- include/_builtin_common.h
- include/_builtin_stdio_checked.h
- include/_builtin_string_checked.h
- include/inttypes_checked.h
- include/math_checked.h
- include/stdio_checked.h
- include/stdlib_checked.h
- include/string_checked.h
- include/time_checked.h
This change updates our checked wrappers for C standard libraries to use null-terminated array pointers for strings.
- I expanded the list of string functions and had to disable more optimized macros for GCC.
- In cases where I could make some parameters a function checked, but not other parameters checked,
I went ahead and did that.  This include functions such as `strcat` and `strncat`.   The fact that the destination buffer has an unchecked pointer type should be a warning to programmers trying to use them.
- For `strncat`, we have no way of expressing the bounds requirement in checked code, because the bounds requirement involves a function call.
Testing:
- Passed automated testing, including LNT testing.
> Use null-terminated array pointers in checked wrappers for C standard libraries

- include/_builtin_stdio_checked.h
- include/_builtin_string_checked.h
- include/stdio_checked.h
- include/string_checked.h
- include/unistd_checked.h
- tests/typechecking/redeclare_libraries.c
This is a placeholder PR to track me adding the equivalent FORTIFY_SOURCE functions to the checked C headers for string functions. 
I'll be adding more commits this afternoon/evening. I'll comment when it's ready for reviewing/merging.
> Add Fortifiy source support for String Methods

- tests/parsing/pointer_bounds_cast.c
- tests/static_checking/bounds_decl_checking.c
- tests/static_checking/static_check_bounds_cast.c
- tests/typechecking/checked_arrays.c
- tests/typechecking/checked_scope_basic.c
- tests/typechecking/checked_scope_interfaces.c
- tests/typechecking/type_check_bounds_cast.c
We are updating the compiler to do bounds declaration checking for constant-sized ranges (https://github.com/Microsoft/checkedc-clang/pull/414).   This causes new error messages to be produced for a number of tests.  For example, tests for typechecking might pass typechecking (as expected), but then fail bounds declaration checking..  
Update the tests with the expected error messages from clang (most of these errors were expected once enough bounds declaration checking came on-line and were flagged by TODO comments).
As an FYI, there are additional bounds declaration checking tests in the Checked C clang repo.  These contain detailed checks of the expected explanations, and are not placed in the Checked C repo.
The bounds declaration checking detects and gives errors for the bogus …
> Add error messages produced by bounds declaration checking

- tests/dynamic_checking/bounds/deref.c
- tests/dynamic_checking/bounds/deref_opt.c
- tests/dynamic_checking/bounds/nullterm_pointers.c
- tests/dynamic_checking/dynamic-bounds-cast-check.c
- tests/static_checking/bounds_decl_checking.c
Update dynamic tests of runtime bounds checking to suppress these warnings.  We don't expect to see warnings for these tests and turn warnings into errors.
For bounds declaration checking, turn TODO's for expected warnings into pattern matches for the expected warnings.
> Compiler now warns about some out-of-bounds memory accesses.

- include/stdio_checked.h
- include/string_checked.h
This is an annoying change, but sometimes, despite having `_FORTIFY_SOURCE` set to non-zero, the stdlib won't always give a definition for that a symbol that should be fortified (looking at you, Mac OS X 10.13 and unprotected `fprintf`)
This check introduces per-function guards. They define the normal kind of the function if:
- fortify_source == 0; or
- there is no macro for the function.
If fortify_source is zero (ie, we're not using the fortified versions), and the macro is defined, then we need to undefine it, as it's constant folding definition or similar, and we can fall back on the original definition.
Damnit I wish that system headers were more cooperative.
This will need checking on linux please @awruef 
Testing:
- Passes on Mac OS X 10.13.
> Make Fortify-source definitions more fine-grained

- tests/static_checking/bounds_decl_checking.c
- tests/static_checking/initializers.c
- tests/static_checking/static_check_bounds_cast.c
- tests/typechecking/checked_arrays.c
- tests/typechecking/checked_scope_basic.c
- tests/typechecking/checked_scope_interfaces.c
The compiler now always warns when it cannot prove a bounds
declaration true or false in a checked scope.   This adds warnings to tests
where this is the case.  Most of these warnings will disappear when we extend
bounds declaration checking to include facts about equality of
variables/expressions after assignments.
The compiler also understands equivalence of base expressions for
constant-sized regions better.  This lets the compiler deduce that
`*(_Dynamic_bounds_cast<array_ptr<int>>(r, 1) + 2) = 4` will always
fault at runtime.
> Warnings about unprovable bounds declarations in checked scopes.

- tests/static_checking/bounds_decl_checking.c
- tests/static_checking/static_check_bounds_cast.c
- tests/typechecking/checked_arrays.c
- tests/typechecking/checked_scope_basic.c
- tests/typechecking/checked_scope_interfaces.c
- tests/typechecking/checked_scope_pragma.c
- tests/typechecking/pointer_types.c
We are changing the compiler to use the term "unknown bounds" in error messages instead of "no bounds" because "no bounds" is ambiguous (see https://github.com/Microsoft/checkedc-clang/pull/430).  It could mean unbounded or unknown bounds.   Update the error messages that are checked in tests.
Testing:
- Passed automated testing on Windows and Linux.
> Update error messages to use the term "unknown bounds".

- samples/string-helpers.c
- spec/bounds_safety/core-extensions.tex
- spec/bounds_safety/variable-bounds.tex
- tests/dynamic_checking/bounds/nullterm_pointers.c
This change addresses the suggestion from @mwhicks1 in issue #235 that we relax the bounds checking for null-terminated arrays to allow a write of 0 at the upper bound of a null-terminated array.  There will be a matching pull request in the checked-clang repo for compiler change.  
- Update the description of bounds checking in the Checked C specification.
- Add tests to nullterm_pointers.c that check this behavior.
-  Update the sample code in string-helpers.c to delete some special-case code in the "squeeze" function.  This function removes all occurrences of a character from a string.  If no characters are removed, it redundantly overwrites the existing null-terminator.  Before, this had to be special-cased to avoid an out-of-bounds write.   I also updated the sample code to avoid …
> Allow writing a 0 at the upper bound of a null-terminated array.

- tests/runtime_operations/README.md
- tests/runtime_operations/assignments.c
Reading variables with bounds-safe interfaces works fine.  Writing
variables with bounds-interfaces caused a compiler crash. Add a
simple test for writing a variable.  We should add more tests
for writes at bounds-safe interfaces eventually.
I placed this test in a new subdirectory `runtime_operations`. This
will contain tests for checked type operations that are done at
runtime, but don't do dynamic runtime checks.
In this case, there is an implicit cast inserted at bounds-safe interfaces.
We want to make sure those casts operate correctly.
> Test assignment to a variable with a bounds-safe interface.

- tests/static_checking/returns/falloff1.c
- tests/static_checking/returns/falloff2.c
- tests/static_checking/returns/falloff3.c
- tests/static_checking/returns/falloff4.c
- tests/static_checking/returns/falloff5.c
- tests/static_checking/returns/falloff6.c
- tests/static_checking/returns/falloff7.c
- tests/static_checking/returns/falloff8.c
- tests/static_checking/returns/funcbody.c
- tests/typechecking/checked_scope_interfaces.c
C programs can have problems with return statements that would result in undefined or incorrect program behavior. C compilers typically warn about these problems (in other languages, these would typically be compile-time errors because of the severity of the problem).  For Checked C, these problems need to result in errors when they occur in a checked scope or involve bounds or check pointer types.  This
change adds tests for these problems.
> Error messages for problems involving return statements. 

- spec/bounds_safety/checking-variable-bounds.tex
- spec/bounds_safety/interoperation.tex
Update the specification to cover type checking and bounds checking of return statements with bounds-safe interfaces.  This addresses issue #193.
> Return statements with bounds-safe interfaces.

- spec/bounds_safety/core-extensions.tex
Describe extensions to C typing rules that allow literals to be used in checked scopes or where expressions with checked pointers are expected.   This completes the work for issue #207.   For checked scopes, string literals are given the type "null-terminated checked array of character", where "character" is the character type for the string literal.   For contexts where an expression with a checked pointer type is expected but not found, convert string literals and compound array literals to checked pointer types.
Also describe the rules for initializers.   The types of initializers are determined by the  type of the variable being declared, so there isn't any change need for checked C.  
Add examples.
Move the section describing checked scopes earlier in Chapter 2, so that it precedes …
> Checked C typing rules for literals.  Also describe handling of initializers.

- spec/bounds_safety/core-extensions.tex
- spec/bounds_safety/open-issues.tex
- tests/static_checking/initializers.c
Variables with checked pointer type that may be used to access memory must be initialized when they are declared.  This also applies to variables with members or elements with checked pointer type that may be used to access memory.  Update the specification to make this clear.   Include some examples.  This addresses issue #98.
The compiler already checks these requirements for scalar variables.  I opened https://github.com/Microsoft/checkedc-clang/issues/445 to track checking these requirements for struct and array variables.
Add tests for the struct/array cases to the Checked C tests.
> Update description of initialization requirements

- spec/bounds_safety/core-extensions.tex
- spec/bounds_safety/related-work.tex
Fix typographical errors in the specification found during a review of the new section on string literals and compound literals.
> Fix typos found during review of literals section.

- spec/bounds_safety/interoperation.tex
The existing syntax of the *_bound_cast operators is confusing.  The kind
of bounds being specified is not explicit.  It depends on the number of
arguments to the operator.  It is clearer to just use a bounds expression
to describe the bounds.  That involves a little more typing, but it is
easier to understand and allows programmers to use all the different variants
of bounds expressions.
Add examples of using dynamic_bounds_cast and assume_bounds_cast for
clarity.
> Change syntax of *_bounds_cast operators and add examples.

- tests/dynamic_checking/bounds/bounds-safe-interfaces.c
Add runtime testing of reads and writes through pointers with null-terminated interface types.  A pointer with a null-terminated type with no bounds information has a bounds of count(0).  A program can read the element at the pointer and write null.   Other reads/writes will cause bounds checking failures.   This covers https://github.com/microsoft/checkedc-clang/issues/449 and more.
I extended bounds-safe-interfaces.c, which runs a sequence of read/tests, expecting conditions to be set properly for the nth test in the sequence to fail.   For bounds-safe interfaces for null-terminated types, we currently have no way to specify a length.  In this case, the bounds are fixed.  Instead, we vary the position where the read/write occurs to force a failure.
> Add dynamic tests of reads/writes via pointers with null-terminated interface types.

- include/string_checked.h
- tests/parsing/interop_and_bounds.c
- tests/parsing/rel_align.c
- tests/typechecking/checked_scope_interfaces.c
- tests/typechecking/interop_type_annotations.c
- tests/typechecking/redeclarations.c
- Test parsing and typechecking of bounds-safe interfaces with interface types and bounds expressions.
- Test redeclarations of functions and variables with bounds-safe interfaces with interface typese and bounds expressions.
- Add tests of bounds-safe interface in checked scopes that cover the different forms of bounds expressions.  This includes a test case that covers https://github.com/Microsoft/checkedc-clang/issues/443.
- Add tests of redeclarations involving `nt_array_ptr`.
- Fix bounds-safe interface for `strtok`: the compiler isn't properly inferring that return types of the form `nt_array_ptr<char>` have bounds of `count(0)`.  We can just declare the bounds of `count(0)` for now.
> Test interface types combined with bounds expressions.

- spec/bounds_safety/related-work.tex
Added paragraph for "Stack Bounds Protection with Low Fat Pointers" (NDSS 2017) as well as a reference to the open source implementation of the research prototype.
> Text for LowFat Stack Bounds Protection, NDSS17

- include/string_checked.h
- tests/typechecking/redeclarations.c
Remove inferred return bounds workarounds. Add inferred parameter bounds tests:
- Update tests now that the compiler properly infers return bounds of count(0)
for nt_array_ptr return types.
- Remove workaround for strtok from checked header files.
- Add more tests of inference of bounds/itypes for parameters.  This includes
tests that mix parameter types that are pointers and arrays, as well as
tests of inferred bounds of nt_checked arrays parameters.
The tests are for the compiler change at https://github.com/Microsoft/checkedc-clang.
> Tests for inferred return bounds.

- tests/dynamic_checking/bounds/bounds-safe-interfaces.c
We recently added compiler support for declaring bounds-safe interfaces that have interop types and bounds expressions.  Add tests of runtime bounds checking involving parameters declared this way.   The variables are declared in unchecked scopes and used in checked scopes.   Add tests for these combinations:
- checked array interop types.  This implies bounds that are the count of the first dimension of the array.
- array_ptr interop types with bounds expressions.
- nt_array_ptr interop types with bounds expressions.
We already had a test of nt_array_ptr with no bounds expression, which implies bounds of count(0).
> Test bounds checking of interop types with bounds expressions.

- tests/dynamic_checking/bounds/deref.c
- tests/parsing/declaration_bounds.c
- tests/parsing/pointer_bounds_cast.c
- tests/parsing/rel_align.c
- tests/static_checking/bounds_decl_checking.c
- tests/static_checking/initializers.c
- tests/static_checking/lexical_equality.c
- tests/static_checking/static_check_bounds_cast.c
- tests/typechecking/bounds.c
- tests/typechecking/checked_arrays.c
- tests/typechecking/checked_scope_interfaces.c
- tests/typechecking/interop.c
- tests/typechecking/pointer-sized-long-long/pointer_casts.c
- tests/typechecking/pointer-sized-long/pointer_casts.c
- tests/typechecking/pointer_types.c
- tests/typechecking/redeclarations.c
- tests/typechecking/type_check_bounds_cast.c
This matches a compiler change that turns on checking of bounds declarations everywhere and teaches the compiler about simple equality facts (PR https://github.com/Microsoft/checkedc-clang/pull/476).
Checking of bounds declarations is a static analysis that checks that declared bounds are valid (follow from existing bounds and other information in the environment). It was only on by default for checked scopes.  It is now on by default for unchecked scopes too.   The checking of bounds declarations is still simple, so it may produce unnecessary warnings.   It can be turned off using  `-Wno-check-bounds-decls` (everywhere), `-Wno-check-bounds-decl-unchecked-scope` (for unchecked scopes), and `-Wno-check-bounds-decls-checked-scope` (for checked scopes), 
- Added more tests of expression …
> Checking of bounds declarations everywhere, expression equality facts.

- tests/typechecking/function_casts.c
A programmer reported that a function call involving a const member with checked function pointer type resulted in an unexpected compiler error (https://github.com/Microsoft/checkedc-clang/issues/481).   This is due to a compiler bug.  This change improves the testing of function pointer casts.
- Add tests of assignments to members with function pointer types.
- Add tests of calls via members with function pointer types.
- Add tests of uses of const members with function pointer types.  These
uses include member reads, member writes, and indirect calls via members.
- Add case from programmer bug report.
- Spot check uses of members with bounds-safe interfaces that are checked
function pointer types.
The compiler bug will be fixed by PR https://github.com/Microsoft/checkedc-clang/pull/482. …
> Improve tests for function pointers casts.

- tests/typechecking/checked_scope_interfaces.c
- tests/typechecking/interop_type_annotations.c
The compiler crashed when `signal` with a bounds-safe interface was called in a checked scope.  PR https://github.com/Microsoft/checkedc-clang/pull/483 fixes this.    This change adds more tests of type checking of function that return function pointers, including testing uses in and outside of checked scopes.
> Test uses of functions that return function pointers with bounds-safe interfaces

- spec/bounds_safety/checkedc.tex
- spec/bounds_safety/core-extensions.tex
- spec/bounds_safety/interoperation.tex
- tests/typechecking/interop_type_annotations.c
I plan to release an updated version of the spec because the BOUNDS_CHECKED pragma has been renamed to CHECKED_SCOPE.  Address some other issues where the specification doesn't match the implementation.
- Address issue #100 (update motivation and definitions of explicit dynamic check).  Add a statement that for dynamic_check(e), e must be nonmodifying.
- Address issue #269.  Update specification to allow an interop type and a bounds expression as part of a bounds-safe interface.
- Change the wording to be clear that bounds-safe interface can be applied to unchecked arrays too.  This addresses some feedback in issue #272.
- Remove the requirement that every parameter for a function or every member of a struct/member must be annotated with a bounds-safe interface, if one of them is …
> Update specification to match implementation.

- tests/static_checking/address_of.c
- tests/static_checking/bounds_decl_checking.c
Checked C restricts taking the addresses of:
1. Members with member bounds declarations.
2. Members used in member bounds declarations.
3. Variables with bounds declarations.
4. Variables/variable members used in bounds declarations.
This add tests of restrictions 1-3, as part of implementing https://github.com/Microsoft/checkedc-clang/issues/213 and https://github.com/Microsoft/checkedc-clang/issues/212:
- Taking the address of non-array members with or used in bounds declarations is now an error. 
- Taking the address of non-array members with or used in bounds-safe interfaces is allowed in unchecked scopes.  It is an error in checked scopes.
- Taking the address of non-array variables with bounds declaration is now an error.
It is OK to take the address of an array variable or member …
> Test restrictions on taking addresses of members and variables.

- include/CMakeLists.txt
unistd_checked.h was missing from CMakeLists and couldn't be found by Clang. This change adds it.
> Add unistd_checked.h to CMakeLists.txt

- include/CMakeLists.txt
- include/checkedc_extensions.h
- include/stdlib_checked.h
- include/string_checked.h
- tests/typechecking/redeclare_libraries.c
Added a new header `checkedc_extensions.h` which specifies extra bounds-safe interfaces that can be chosen by the programmer when functions have different interfaces for `array_ptr` and `nt_array_ptr`. Added it to the `CMakeLists.txt` in the include folder and added it to the header inclusion test `tests/typechecking/redeclare_libraries.c`. Passes this test and functions properly when compiling example third-party code.
Addresses #291 and #290
> New header with additional bounds-safe interfaces

- include/fenv_checked.h
- include/inttypes_checked.h
- include/math_checked.h
- include/signal_checked.h
- include/stdio_checked.h
- include/stdlib_checked.h
- include/string_checked.h
- include/threads_checked.h
- include/time_checked.h
- include/unistd_checked.h
Our standard library bounds safe interface headers didn't have guards. This fixes that.
(Completed entirely while code was compiling...)
> Add header guards

- include/CMakeLists.txt
- include/errno_checked.h
- tests/typechecking/errno-use.c
- tests/typechecking/redeclare_libraries.c
One of the files I'm converting uses `errno`. This makes CheckedC unhappy because the function that makes errno (inside a layer of macros) returns an `int*`. This PR adds a new `errno_checked.h` header file to provide a bounds-safe interface for that function. It passes the `redeclare_libraries` test and gets rid of the errors in my converted file. `errno.h` is a short header; I believe this is the only function.
> Bounds-safe interface for function in errno

- include/checkedc_extensions.h
- include/stdlib_checked.h
We decided to change the bounds-safe interface requirement of the argument passed to free to be byte_count(0) rather than byte_count(1). This means we no longer need the extra version of free in checkedc_extensions, or several lines of commentary.
Addresses #290
> Require byte_count(0) of the arg to free

- include/string_checked.h
Explanation in issue #300.
Fixes #300.
> memmove should not have restrict on arguments.

- include/CMakeLists.txt
- include/assert_checked.h
- tests/typechecking/redeclare_libraries.c
Both Windows and Linux have some interesting things going on with their use of assert. Add a new header with bounds-safe interface for the function eventually called by assert macros in the case of failure.
> Bounds-safe interface for assert

- tests/typechecking/itype_generic_functions.c
- tests/typechecking/redeclarations.c
Parsing logic of _For_any and _Itype_for_any seems to fail in linux.
Merging this PR must wait until the root cause is found and fixed.
> Adding support for polymorphic bounds safe interface functions.

- include/stdchecked.h
- tests/parsing/return_bounds.c
- tests/typechecking/bounds.c
- tests/typechecking/checked_scope_basic.c
- tests/typechecking/checked_scope_interfaces.c
- tests/typechecking/redeclarations.c
This changes add tests for parsing and type checking of return_value expressions.  This matches the compiler pull request at https://github.com/Microsoft/checkedc-clang/pull/544.
> Tests for parsing and type checking return_value expressions.

- include/assert_checked.h
I have come across code that uses `__assert_fail` on Linux. Here's a bounds-safe interface for it.
> Adds bounds-safe interface for __assert_fail on Linux

- include/checkedc_extensions.h
- include/stdio_checked.h
Since `snprintf` always puts a null-terminator for `n > 0`, I propose that we adjust the bounds-safe interface for `snprintf` slightly to reflect that the destination buffer will be null-terminated and can be 1 unit shorter than `n`. This allows for the fairly common idiom of 
```
char foo _Nt_checked[##];
snprintf(foo, sizeof(foo), formatStr, ...)
```
without any code changes beyond changing the type of foo to be checked.
> Propose change to snprintf bounds-safe interface

- include/arpa/inet_checked.h
- include/sys/socket_checked.h
My example code was not picking up the bounds-safe interfaces in socket_checked and inet_checked. When I remove the checks for POSIX it does pick them up correctly. Passes checkedc tests.
> Remove POSIX checks in socket, inet

- include/stdlib_checked.h
- include/string_checked.h
- tests/typechecking/malloc_free.c
Signatures of memcpy, bsearch and realloc are modified to make them polymorphic bounds safe interface functions
> Making Memcpy, bsearch, realloc  polymorphic generic functions

- include/CMakeLists.txt
We added some new include files for POSIX in subdirectories last week.  The
build system was changed to try to use cmake functionality for recursively
installing a directory and its subdirectories.  This caused the build
of the Windows isntaller to break.
The fix is to revert last week's change and install the new subdirectories
individually.  This is the approach used in clang\lib\Headers\CMakeLists.txt.
This addresses https://github.com/Microsoft/checkedc-clang/issues/562.
Testing:
- Locally built a Windows installer.
> Fix failing Windows installer build.

- tests/typechecking/bounds.c
The compiler no longer emits a duplicate error message for a test. We can remove the comment about needing to fix this.
> Remove comment about issue that has been fixed.

- tests/parsing/return_bounds.c
- tests/typechecking/checked_scope_basic.c
We've updated the compiler to treat _Checked as a function declaration specifier, unless it is followed by a `{` or a `[`.  Update a few tests involving incorrect declarations using _Checked/
> In declarations, treat _Checked as a declaration specifier

- include/stdchecked.h
- tests/typechecking/checked_scope_basic.c
- tests/typechecking/checked_scope_bounds_only.c
By default, checked scopes will include compile-time checks to prevent type
confusion.  The checks will restrict pointer casts, for example. If a
programmer wants only checks for bounds safety, a programmer can modify a
checked scope using the _Bounds_only modifier:
checked bounds_only { ... }
This change adds tests of checked scopes with the new bounds_only modifier.
We haven't implemented the restrictions on pointer casts yet, so the tests
check only that checked scopes with bounds_only modifiers implement the same
restrictions that regular checked scopes currently do.
The change parameterizes checked_scope_basic.c by a #define that adds
a scope modifier optionally..  We create a dummy file to compile the alternate
version of the file.
> Add tests of _Bounds_only modifier for checked scopes.

- tests/static_checking/initializers.c
An error message for integer members with bounds used the term "variable" where the term "member" should be used.
> Fix error message in test.

- tests/parsing/pointer_bounds_cast.c
- tests/parsing/typevariable/generic_func_parsing_error.c
- tests/typechecking/itype_generic_functions.c
- tests/typechecking/redeclarations.c
We've revamped the implementation of generic functions in the compiler:
- Add tests of ways functions with generic types and non-generic types can be incompatible.
- We are now parsing type argument lists based on mostly syntactic information.  This causes misnamed bounds cast operations to be treated as applications of functions to generic type arguments.
- A few error messages changed.
> Update tests after revamping implementation of generic functions

- tests/typechecking/pointer_types.c
We are disallowing some implicit void pointer conversions in memory-safe checked scopes.    Conversions between void pointer types and non-void pointer types are disallowed when the non-void type contains a checked pointer value within it.   This allows pointers to integer and non-pointer data to be converted to and from void pointers.  It  prevents type confusion problems that can lead to data corruptions that allow out-of-bounds memory accesses. 
PR https://github.com/Microsoft/checkedc-clang/pull/590 implements this in the Checked C clang compiler.
Add tests for implicit void pointer conversions in different kinds of checked scopes.  Also add new tests for implicit conversions at return statements.
Testing:
- Passed automating testing on Linux and Windows.
> Test implicit void pointer conversions in different kinds of checked scopes.

- tests/typechecking/generic_type_arguments.c
There were a number of cases where the compiler did not infer bounds for call expressions that call functions with return bounds.  We left those cases unchecked by using Bounds(any) for them.
We're adding these cases to the compiler (PR https://github.com/Microsoft/checkedc-clang/pull/597) , which causes more warning messages about bounds declaration not being provable.
- Update the tests with these new warning messages.
- We can improve the checking of bounds declarations to eliminate these messages.  Mark the new warnings with Github issues tracking this work.
The missing cases were count and byte_count return bounds, as well as returning _Ptr values.
> Update test cases for call expressions with return bounds.

- tests/typechecking/pointer-sized-long-long/lit.local.cfg
- tests/typechecking/pointer-sized-long/lit.local.cfg
Some automated tests are failing on Windows x64 after updating the LLVM/clang sources.   The tests are platform-specific and aren't supposed to be run on 64-bit Windows targets.    The target platform name for Windows changed in the LLVM test infrastructure, which caused this failure.
> Fix failing tests on Windows x64.

- include/string_checked.h
Adding CheckedC type for `strdup` using `itype`
> Adding CheckedC type for strdup.

- spec/bounds_safety/core-extensions.tex
- Fixed multiple typos or grammar errors in Chapter 2.10 and 2.11.
- At line 1305 of core-extensions.tex, the two ampersands look weird.
> Fixed typos or grammar errors in the spec.

- tests/typechecking/checked_scope_basic.c
Added a function to test explicit casts to nt_array_ptr in a checked
scope. Only casting from nt_array_ptr to nt_array_ptr is allowed;
other explicit casts from ptr or array_ptr to nt_array_ptr are
disallowed.
Also added code to test casting from ptr, array_ptr, and unchecked
pointers to nt_array_ptr in a unchecked scope.
> Added tests on explicit cast to nt_array_ptr in checked scopes.

- tests/dynamic_checking/dynamic_check/simple-pass.c
Added two lit variables:
1. %checkedc_target_flags: target-specific triple and sysroot flags.
2. %checkedc_rununder: target-specific run host, like qemu.
> Add new lit variables to support ARM testing in lit

- tests/dynamic_checking/bounds/array-bounds-decls.c
- tests/dynamic_checking/bounds/bounds-safe-interfaces.c
- tests/dynamic_checking/bounds/deref.c
- tests/dynamic_checking/bounds/deref_arith.c
- tests/dynamic_checking/bounds/deref_arith_call_expr.c
- tests/dynamic_checking/bounds/deref_arith_call_expr_opt.c
- tests/dynamic_checking/bounds/deref_arith_opt.c
- tests/dynamic_checking/bounds/deref_arrow_member_expr.c
- tests/dynamic_checking/bounds/deref_arrow_member_expr_opt.c
- tests/dynamic_checking/bounds/deref_dot_member_expr.c
- tests/dynamic_checking/bounds/deref_dot_member_expr_opt.c
- tests/dynamic_checking/bounds/deref_opt.c
- tests/dynamic_checking/bounds/nullterm_pointers.c
- tests/dynamic_checking/bounds/subscript.c
- tests/dynamic_checking/bounds/subscript_arrow_member_expr.c
- tests/dynamic_checking/bounds/subscript_arrow_member_expr_opt.c
- tests/dynamic_checking/bounds/subscript_call_expr.c
- tests/dynamic_checking/bounds/subscript_call_expr_bsi.c
- tests/dynamic_checking/bounds/subscript_call_expr_opt.c
- tests/dynamic_checking/bounds/subscript_dot_member_expr.c
- tests/dynamic_checking/bounds/subscript_dot_member_expr_opt.c
- tests/dynamic_checking/bounds/subscript_opt.c
- tests/dynamic_checking/dynamic_check/arith-fail.c
- tests/dynamic_checking/dynamic_check/arith-pass.c
- tests/dynamic_checking/dynamic_check/simple-fail.c
Added the following to all tests under dynamic_checking:
1.  %checkedc_target_flags to all clang compile RUN lines.
2. %checkedc_rununder to all execution RUN lines.
> Enable dynamic_checking tests for ARM

- tests/dynamic_checking/bounds/predefined_literals.c
Test that predefined literals actually work when assigned to checked ptrs. Current tests only checks sanity of predefined literals. Can add more tests in future.
> Add run time tests for predefined literals

- tests/static_checking/lexical_equality.c
- tests/static_checking/static_check_bounds_cast.c
This PR adds tests for microsoft/checkedc-clang#694:
* Lexical equality tests to ensure that _Dynamic_bounds_cast and _Assume_bounds_cast expressions are not treated as value-preserving in function redeclarations.
* Memory access checks involving _Dynamic_bounds_cast and _Assume_bounds_cast expressions have the correct inferred bounds.
The expected out-of-bounds memory access warning has also been disabled in static_check_bounds_check.c. microsoft/checkedc-clang#695 tracks the work necessary to re-enable this warning.
> Add tests for bounds cast expression temporary bindings

- tests/typechecking/static_variables_free_type_variables.c
(See microsoft/checkedc-clang#684)
Add typechecking tests to verify that declarations of static variables cannot use free type variables.
> Add typechecking tests for static declarations involving free type variables

- tests/static_checking/static_check_bounds_cast.c
Re-enable the expected out-of-bounds memory access warning for a bounds cast expression, and add additional out-of-bounds memory access testing for a bounds cast expression involving an array access.
> Re-enable out-of-bounds memory access warning

- tests/dynamic_checking/bounds/deref.c
- tests/dynamic_checking/bounds/deref_opt.c
- tests/dynamic_checking/bounds/nullterm_pointers.c
- tests/dynamic_checking/bounds/predefined_literals.c
- tests/dynamic_checking/dynamic-bounds-cast-check.c
- tests/runtime_operations/assignments.c
- tests/static_checking/bounds_decl_checking.c
- tests/static_checking/static_check_bounds_cast.c
This is to update the tests to match the new handling of empty and invalid ranges. The corresponding code for the new handling is in this [pull-request](https://github.com/microsoft/checkedc-clang/pull/707).
> Matching tests to the new logic on handling empty/invalid ranges

- tests/dynamic_checking/bounds/nullterm_pointers.c
After we have established that the value at the upper bound of an nt_array_ptr
s is non-null, we widen its bounds by 1. So the new upper bound of s is
(curr upper bound + 1). So in order to test writing at the upper we need to
write to *(s+1) instead of *s.
> Fix checkedc unit test after bounds widening

- tests/dynamic_checking/bounds/deref_arith_call_expr.c
- tests/dynamic_checking/bounds/deref_arith_call_expr_opt.c
- tests/dynamic_checking/bounds/subscript_call_expr.c
- tests/dynamic_checking/bounds/subscript_call_expr_bsi.c
- tests/dynamic_checking/bounds/subscript_call_expr_opt.c
- tests/dynamic_checking/dynamic-bounds-cast-check.c
- tests/static_checking/bounds_decl_checking.c
- tests/static_checking/initializers.c
- tests/static_checking/static_check_bounds_cast.c
- tests/typechecking/checked_scope_basic.c
This PR modifies the Checked C tests to reflect the changes in [checkedc-clang/857](https://github.com/microsoft/checkedc-clang/pull/857).
The PR for bounds context validation [checkedc-clang/853](https://github.com/microsoft/checkedc-clang/pull/853) introduced bounds checking warnings due to missing equality information between a variable target and a source expression that was not included in CheckingState.EquivExprs. This PR removes those expected warnings from the tests due to the checkedc-clang PR to fix the extra warnings.
> Record equality between target and source: tests

- samples/string-helpers.c
- spec/bounds_safety/core-extensions.tex
- spec/bounds_safety/introduction.tex
- spec/bounds_safety/variable-bounds.tex
Trailing spaces are removed. Please let me know if this is undesired.
> Fix typos and spacing in spec and samples.

- spec/bounds_safety/interoperation.tex
See issue #397 
This PR adds some missing cases for bounds-safe interface assignment compatibility to section 6.3.6 (Interoperation - Type checking).
> Update spec to include missing cases for bounds-safe interface assignments

- tests/parsing/pointer_bounds_cast.c
- tests/static_checking/bounds_decl_checking.c
- tests/static_checking/static_check_bounds_cast.c
- tests/typechecking/pointer_types.c
- tests/typechecking/type_check_bounds_cast.c
This PR updates checked-c tests to add expected warnings and errors since the checkedc-clang PR [836](https://github.com/microsoft/checkedc-clang/pull/836) updates the observed bounds context after an assignment to a variable.
> Bounds context: update after assignments (tests)

- tests/typechecking/checked_arrays.c
- tests/typechecking/interop.c
This PR adds Checked C tests for clang PR [#813](https://github.com/microsoft/checkedc-clang/pull/813), which fills in two missing cases for bounds-safe interface assignment compatibility.
> Add tests for bounds-safe interface assignments

- tests/typechecking/function_casts.c
This PR adds tests for the use of _Assume_bounds_casts to convert unchecked function pointers to checked function pointers (implementation in [checkedc-clang/865](https://github.com/microsoft/checkedc-clang/pull/865)).
> Allow assume bounds casts for function pointers: tests

- include/string_checked.h
We need to `undef strdup` to avoid conflicts with GNU's `strdup`.
> Undefing strdup in the case of GCC

- spec/bounds_safety/introduction.tex
This addresses an incomplete sentence in the introduction of the Checked C specification, pointed out by issue #355 .
> Fix incomplete sentence in introduction.

- spec/bounds_safety/checking-variable-bounds.tex
This changes simplifies the description of bounds declaration checking to use read/write sets of pending variable sets.  
Currently we are using a notion of pending variables in the description of checking of bounds declarations. They are computed by another function that is called during checking. This doesn't extend well to lvalue expressions because lvalue expressions depend on variables, which may be modified within an expression.
This change replaces pending variables with read/write summaries.  This allows a bottom computation of a summary of the effects of an expression.  We can then determine if the read/write summary for expression with an unspecified order of evaluation with respect to each other conflict. The read/write summaries for lvalue expressions can use variables defined …
> Introduce read/write sets for bounds declaration checking description.

- tests/static_checking/bounds_decl_checking.c
This PR adds tests for [checkedc-clang/899](https://github.com/microsoft/checkedc-clang/pull/899). Since all compound literals are bound to temporaries, lvalue bounds can be inferred for array and struct-typed compound literal expressions.
> Add tests for compound literal lvalue bounds

- tests/static_checking/bounds_decl_checking.c
This PR fixes the two new expected errors introduced by #414 to reflect the changes in #412 - expecting 'declared bounds for ... are invalid after initialization' rather than 'declared bounds for ... are invalid after statement'.
> Change expected errors to 'initialization' rather than 'statement'

- spec/bounds_safety/checkedc.tex
I'll probably install `parskip.sty` to match what your configuration must have been to successfully produce the released specs, but as long as you have this code path at all, it should work.
> spec: Fix typo that blocks the build when parskip.sty is not installed.

- spec/bounds_safety/checking-variable-bounds.tex
Fixes #416 
This PR updates the description of the algorithm for checking a conditional expression `e1 ? e2 : e3`.
The set of equivalent expression sets used to check each arm `e2` and `e3` should be the set of equivalent expressions that was true after checking the test expression `e1`. Consider:
```
void f(array_ptr<int> a : count(1), array_ptr<int> b : count(2)) {
(a = b) ? a : b;
}
```
The equality between `a` and `b` that is recorded in the test expression `e1` should be true at the end of checking the conditional expression. The final observed bounds context is `{ a => bounds(b, b + 2), b => bounds(b, b + 2) }`. The final set of equivalent expressions should contain `{ a, b } ` in order to check the updated observed bounds of `a`.
The final observed bounds context after checking a …
> Update description of checking conditional expressions

- README.md
Added a talk titled "Checked C: Adding memory safety support to LLVM" that we
presented at the 2020 LLVM Virtual Dev Meeting.
> Add talk - Checked C: Adding memory safety support to LLVM

- spec/bounds_safety/variable-bounds.tex
Fixed a typo in Section 3.9.2, in the runtime check inserted when rel_align is specified.
> Fixed a typo.

- tests/typechecking/checked_arrays.c
- tests/typechecking/pointer_types.c
This PR adds expected warnings and errors to tests that result from inferring rvalue bounds for conditional expressions (in [checkedc-clang/924](https://github.com/microsoft/checkedc-clang/pull/924)).
> Update tests for conditional rvalue bounds

- tests/static_checking/initializers.c
Added tests for checkedc-clang PR #942.
> Test for _Nt_checked array initializer sizes

- tests/dynamic_checking/bounds/deref_arith_call_expr.c
- tests/dynamic_checking/bounds/deref_arith_call_expr_opt.c
- tests/dynamic_checking/bounds/subscript_call_expr_bsi.c
- tests/dynamic_checking/bounds/subscript_call_expr_opt.c
There is a small typo in tests/dynamic_checking/bounds/deref_arith_call_expr.c, tests/dynamic_checking/bounds/deref_arith_call_expr_opt.c, tests/dynamic_checking/bounds/subscript_call_expr_bsi.c, tests/dynamic_checking/bounds/subscript_call_expr_opt.c.
Should read `perform an` rather than `performanc`.
> docs: fix simple typo, performanc -> perform an

- tests/parsing/pointer_bounds_cast.c
The parsing/pointer_bounds_cast.c test expected an error where the bounds of 'x' are invalid after a dynamic bounds cast. The actual error is that it is impossible to prove that the bounds of 'x' are valid since there is no relational information between the variables 'cache1' in the inferred bounds and 'x' in the declared bounds.
> Fix failing test resulting from free variables merge

- tests/parsing/member_bounds.c
- tests/parsing/pointer-larger-int/lit.local.cfg
- tests/parsing/pointer-larger-int/member_bounds.c
- tests/typechecking/bounds.c
- tests/typechecking/pointer-larger-int/bounds.c
- tests/typechecking/pointer-larger-int/lit.local.cfg
- tests/typechecking/pointer-larger-long/bounds.c
- tests/typechecking/pointer-larger-long/lit.local.cfg
- tests/typechecking/pointer-sized-long-long/pointer_casts.c
- tests/typechecking/pointer-sized-long/pointer_casts.c
Update some Checked C test files to account for changes made to checkedc-clang during the upgrade to Clang/LLVM 11.0 (see the updated-master-11-last branch of checkedc-clang).
> Clang 11 upgrade: update Checked C tests

- spec/bounds_safety/interoperation.tex
* Include documentation on function pointer types and type annotations.
* Related to issue [#1027](https://github.com/microsoft/checkedc-clang/issues/1027) in the clang repo.
> Update documentation for using function pointers

- tests/dynamic_checking/bounds/bounds-safe-interfaces.c
- tests/static_checking/bounds_decl_checking.c
This PR updates test files to account for the new compiler behavior introduced by [checkedc-clang/1083](https://github.com/microsoft/checkedc-clang/pull/1083): validating the bounds context for member expressions. The compiler now emits errors and warnings for statements that invalidate member bounds by assigning to member expressions that are used in member bounds.
> [LValue Generalization] Update tests for validating member bounds

- tests/static_checking/initializers.c
Fixing a unit test in response to PR https://github.com/microsoft/checkedc-clang/pull/1121
See issue https://github.com/microsoft/checkedc-clang/issues/1120
> An nt_checked array with an empty initializer list should be an error

- tests/typechecking/checked_scope_basic.c
This PR updates tests for [checkedc-clang/1135](https://github.com/microsoft/checkedc-clang/pull/1135). When the new method `GetVariableAndConstant` is used to compare two upper bounds expressions, the bounds checker is able to prove that the inferred bounds `bounds(arr, arr + 5)` are equivalent to the required cast bounds `bounds((_Array_ptr<int _Checked[]>)&arr, (_Array_ptr<int _Checked[]>)&arr + 1))`
> Get variable and constant: update tests

- spec/bounds_safety/core-extensions.tex
- spec/bounds_safety/interoperation.tex
- spec/bounds_safety/void-ptr-replacements.tex
Fixed several typos and missed words in Chapter 2, 3 and 5 of the Language Specification.
> [spec] Fixed typos and missed words in Chapter 2, 5, and 6.

- tests/static_checking/bounds_decl_checking.c
- tests/typechecking/pointer_types.c
This PR updates the tests to reflect the updated type checking behavior for address-of array subscripts in [checkedc-clang/1163](https://github.com/microsoft/checkedc-clang/pull/1163). If an expression `e` has type `T`, then `&e[idx]` and `&idx[e]` also have type `T`.
> Treat address-of array subscripts the same way as address-of dereferences: update tests

- tests/typechecking/checked_scope_pragma.c
https://github.com/microsoft/checkedc-clang/pull/1174 added support to call
variadic functions like printf/scanf, etc within checked scope. As a result,
tests that check for errors if such functions are invoked in checked scope
started failing. We fix one such test in this PR.
> Fix a test that invokes variadic functions in checked scope

- spec/bounds_safety/interoperation.tex
This PR updates the Checked C specification as per the discussions that we have been having about bounds validation when both checked and unchecked pointers (with bounds-safe interfaces) appear in an assignment expression or a function call in an unchecked scope.
Ref: [#1158](https://github.com/microsoft/checkedc-clang/issues/1158), [#1157](https://github.com/microsoft/checkedc-clang/issues/1157), [#1159](https://github.com/microsoft/checkedc-clang/issues/1159) and [PR #1150](https://github.com/microsoft/checkedc-clang/pull/1150).
> Clarification updates to the Checked C specification.

- tests/static_checking/bounds_decl_checking.c
This PR updates some expected error messages to reflect the behavior in [checkedc-clang/1176](https://github.com/microsoft/checkedc-clang/pull/1176): for a pointer dereference or array subscript with target bounds, bounds validation uses the existing framework in `UpdateAfterAssignment` and `ValidateBoundsContext` to validate these expressions. This means that the error messages emitted for pointer dereferences or array subscripts whose inferred bounds are unknown have been updated to be consistent with the error messages for checking variables and member expressions, so the expected error messages in the test file bounds_decl_checking.c are updated.
> Bounds checking for pointer dereferences and array subscripts: update test

- tests/dynamic_checking/bounds/bounds-safe-interfaces.c
This PR updates the bounds-safe-interface test file to account for the changes in [checkedc-clang/1183](https://github.com/microsoft/checkedc-clang/pull/1183).
With this change, the bounds for the value of the member expression `s1->f` are the observed bounds for `s1->f` as recorded in `CheckingState.ObservedBounds`. This means that, after the assignment `s1->len = 0`, the observed bounds for `s1->f` are `bounds(unknown)`. This results in an error when attempting to use `s1->f` in a dynamic bounds cast.
This PR uses an initial dynamic bounds cast so that the observed bounds of `s1->f` are depending on a temporary variable rather than `s1->len`, so that the assignment to `s1->len` does not impact the observed bounds of `s1->f`.
> Get lvalue observed bounds: update test
