microsoft/checkedc

spec/bounds_safety/checkedc.tex

Update the version number to be a draft of version 0.6.

Update version number for specification.

---

tests/typechecking/bounds.c

Also test typechecking of byte_count bounds expressions.

Test typechecking of count bounds expressions.

---

tests/typechecking/function_casts.c

These are the tests for Microsoft/checkedc-clang#125

Adds tests for function pointer casts

---

samples/2_3_1_add.c
samples/2_7_checked.c
samples/2_8_append.c
samples/3_11_compare.c
samples/3_11_sum.c
samples/3_2_1_add.c
samples/3_2_1_find.c
samples/3_2_1_sum.c
samples/3_2_1_sum_extern.c
samples/3_2_2_find.c
samples/3_4_array_ptr.c
samples/3_4_ptr.c
spec/bounds_safety/variable-bounds.tex

These samples of Checked C code have all been extracted from the specification, chapter 1-3.

Adds Samples

---

tests/dynamic_checking/deref-arith-check-opt.c
tests/dynamic_checking/deref-arith-check.c
tests/dynamic_checking/deref-check-opt.c
tests/dynamic_checking/deref-check.c
tests/dynamic_checking/subscript-check-opt.c
tests/dynamic_checking/subscript-check.c

These are tests to go with Microsoft/checkedc-clang#163

Tests of Dynamic Checks at Array Subscript and Deref

---

tests/parsing/rel_align.c

Adds the test code for relative expression. ( rel_align.c )
. extract the range bounds expression from declaration_bounds.c, member_bounds.c and return_bounds.c and add rel_align(char).

Adds the test code for parsing the relative expressoin. (#037)

---

tests/typechecking/checked_scope.c
tests/typechecking/checked_scope_pragma.c

- unchecked  scope keyword clears checked function specifier
check unchecked compound statement with checked function specifier
- unchecked scope clears checked property & prevents inheritance of checked property
check unchecked block with nested checked block (compound statement, structure)

Add test code for unchecked scope (#203)

---

spec/bounds_safety/introduction.tex

This is undoubtedly arrogant and/or cheeky.

Add Myself to Acknowledgements

---

spec/bounds_safety/checkedc.tex
spec/bounds_safety/interoperation.tex

Mark this as the final draft of version 0.7 and fix an undefined reference.

Finalize version 0.7 of the specification.

---

spec/bounds_safety/sources.bib

Added reference to "Stack Object Protection with Low Fat Pointers", NDSS 2017

Stack Object Protection with Low Fat Pointers, NDSS17

---

tests/dynamic_checking/dynamic-bounds-cast-check.c

A user reported an internal compiler crash (https://github.com/Microsoft/checkedc-clang/issues/458).   This change adds additional testing for the compiler fix (https://github.com/Microsoft/checkedc-clang/pull/466):
- Test failing dynamic_bounds_cast operations that convert to ptr<int>.
- Test passing and failing dynamic_bounds_cast operations that
convert to ptr<void> and void *.   These casts can fail if the
source range does not have at least one byte in it.

Improve runtime tests of dynamic_bounds_cast<ptr<T>> operations.

---

README.md

Add a pointer to the compiler installer.

Update readme.md for repo.

---

tests/static_checking/nme_bounds.c

The current specification rules for inferring bounds for an expression can lead to inferred bounds that contain modifying expression.   These aren't allowed.  Add tests that check that the compiler is flagging them  (the Checked C version of clang suggests that the programmer use a temporary variable when this happens).
The particular problematic case that is likely to arise in practice is for member access: `e1.f` and `e1->f`.  If e1 contains a side-effect, we can't expression that bounds for `f` when other members are involved:
```
struct S {
array_ptr<int> p : count(len);
int len;
};
```
`e1 ->p` `has `bounds(e1->p, e1->p + e1->len)`.  This is problematic if `e1` has side-effects.   Note that case where only `e1->p` is involved isn't a problem because we can use `current_expr_value`.

Test disallowing inferred bounds expressions with modifying expressions.

---

include/fenv_checked.h
include/inttypes_checked.h
include/math_checked.h
include/signal_checked.h
include/stdio_checked.h
include/stdlib_checked.h
include/string_checked.h
include/threads_checked.h
include/time_checked.h
include/unistd_checked.h
samples/avoid-warning.c
samples/echo-args-buggy.c
samples/echo-args.c
samples/exit-on-failure.c
samples/find-pattern.c
samples/hello-world.c
spec/bounds_safety/core-extensions.tex
tests/typechecking/checked_scope_basic.c
tests/typechecking/checked_scope_interfaces.c
tests/typechecking/checked_scope_pragma.c
tests/typechecking/function_casts.c
tests/typechecking/malloc_free.c

Update specification and tests.

Rename BOUNDS_CHECKED pragma to CHECKED_SCOPE.

---

include/unistd_checked.h

Add bounds safe interfaces for the unistd functions access, read and write.

Unistd file commands

---

include/stdlib_checked.h
tests/typechecking/malloc_free.c

Changed the signature of malloc, calloc and free to make them polymorphic bounds safe interface functions. 
Testing:
1. Regression tests are modified to have type parameters in calls to malloc, calloc and free
2. LNT tests are updated to have type parameters in calls to malloc, calloc and free

Polymorphic bounds safe interface stdlib functions.

---

tests/dynamic_checking/dynamic-bounds-cast-check.c

There was a compiler assert on a dynamic_bounds_cast of a string literal (https://github.com/Microsoft/checkedc-clang/issues/575).  This is fixed by https://github.com/Microsoft/checkedc-clang/pull/585.   Add runtime tests that check that the right results are being computed in this case.

Test dynamic_bounds_cast involving string literal.

---

tests/typechecking/generic_type_arguments.c

I removed the unnecessary comments following the discussion on #368.

Remove comments about resolved warnings

---

tests/typechecking/generic_structs.c

This PR adds multiple tests that exercise the functionality in https://github.com/microsoft/checkedc-clang/pull/638

Tests for generic structs

---

tests/typechecking/generic_structs.c
tests/typechecking/itype_generic_structs.c

https://github.com/microsoft/checkedc-clang/pull/660 contains the implementation for the feature

Add tests for itypes in generic structs

---

tests/exist_types_runtest/callbacks.c
tests/exist_types_runtest/counters.c
tests/typechecking/existential_structs.c
tests/typechecking/generic_structs.c

Implementation: https://github.com/microsoft/checkedc-clang/pull/683

Add tests for existential structs

---

spec/bounds_safety/related-work.tex
spec/bounds_safety/sources.bib
spec/bounds_safety/void-ptr-replacements.tex

Fixed several typos and citation issues such as wrong citation and
missing citation.

Fixed typos and citations issues.

---

README.md

Update readme 2019 10 18 v2

---

include/errno_checked.h
include/unistd_checked.h

These were not building on my Mac, so added a case for them.

Apple-friendly headers

---

README.md

Updated README with details about the Checked C poster that we presented at the
LLVM Dev Meeting 2019.

Update README with details about the Checked C poster

---

tests/parsing/pointer_bounds_cast.c
tests/static_checking/bounds_decl_checking.c
tests/static_checking/initializers.c
tests/static_checking/static_check_bounds_cast.c
tests/typechecking/pointer_types.c
tests/typechecking/type_check_bounds_cast.c

Update tests for the change https://github.com/microsoft/checkedc-clang/pull/893.

Update tests to reflect improved bounds checking error messages

---

tests/typechecking/bounds.c
tests/typechecking/free-variables.c

Update tests for https://github.com/microsoft/checkedc-clang/pull/919.

Uncomment or remove spurious errors caused by checkedc-clang issue#911

---

spec/bounds_safety/checkedc.tex
spec/bounds_safety/core-extensions.tex
spec/bounds_safety/design-alternatives.tex
spec/bounds_safety/interoperation.tex
spec/bounds_safety/introduction.tex
spec/bounds_safety/variable-bounds.tex
spec/bounds_safety/void-ptr-replacements.tex

I'm just giving you notice that this is coming.  I'm guessing you'd rather wait until my batch of fixes is complete before going to the overhead of reviewing it.

Assorted typo and other minor fixes to the specification.
